// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: aircrafts.proto

package aircraft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AircraftServices_GetAircraft_FullMethodName     = "/targets.AircraftServices/GetAircraft"
	AircraftServices_GetHistory_FullMethodName      = "/targets.AircraftServices/GetHistory"
	AircraftServices_DeleteAircrafts_FullMethodName = "/targets.AircraftServices/DeleteAircrafts"
)

// AircraftServicesClient is the client API for AircraftServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AircraftServicesClient interface {
	GetAircraft(ctx context.Context, in *GetAircraftRequest, opts ...grpc.CallOption) (*GetAircraftResponse, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	DeleteAircrafts(ctx context.Context, in *DeleteAircraftsRequest, opts ...grpc.CallOption) (*DeleteAircraftsResponse, error)
}

type aircraftServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewAircraftServicesClient(cc grpc.ClientConnInterface) AircraftServicesClient {
	return &aircraftServicesClient{cc}
}

func (c *aircraftServicesClient) GetAircraft(ctx context.Context, in *GetAircraftRequest, opts ...grpc.CallOption) (*GetAircraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAircraftResponse)
	err := c.cc.Invoke(ctx, AircraftServices_GetAircraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aircraftServicesClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, AircraftServices_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aircraftServicesClient) DeleteAircrafts(ctx context.Context, in *DeleteAircraftsRequest, opts ...grpc.CallOption) (*DeleteAircraftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAircraftsResponse)
	err := c.cc.Invoke(ctx, AircraftServices_DeleteAircrafts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AircraftServicesServer is the server API for AircraftServices service.
// All implementations must embed UnimplementedAircraftServicesServer
// for forward compatibility.
type AircraftServicesServer interface {
	GetAircraft(context.Context, *GetAircraftRequest) (*GetAircraftResponse, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	DeleteAircrafts(context.Context, *DeleteAircraftsRequest) (*DeleteAircraftsResponse, error)
	mustEmbedUnimplementedAircraftServicesServer()
}

// UnimplementedAircraftServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAircraftServicesServer struct{}

func (UnimplementedAircraftServicesServer) GetAircraft(context.Context, *GetAircraftRequest) (*GetAircraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAircraft not implemented")
}
func (UnimplementedAircraftServicesServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedAircraftServicesServer) DeleteAircrafts(context.Context, *DeleteAircraftsRequest) (*DeleteAircraftsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAircrafts not implemented")
}
func (UnimplementedAircraftServicesServer) mustEmbedUnimplementedAircraftServicesServer() {}
func (UnimplementedAircraftServicesServer) testEmbeddedByValue()                          {}

// UnsafeAircraftServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AircraftServicesServer will
// result in compilation errors.
type UnsafeAircraftServicesServer interface {
	mustEmbedUnimplementedAircraftServicesServer()
}

func RegisterAircraftServicesServer(s grpc.ServiceRegistrar, srv AircraftServicesServer) {
	// If the following call panics, it indicates UnimplementedAircraftServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AircraftServices_ServiceDesc, srv)
}

func _AircraftServices_GetAircraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAircraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AircraftServicesServer).GetAircraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AircraftServices_GetAircraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AircraftServicesServer).GetAircraft(ctx, req.(*GetAircraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AircraftServices_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AircraftServicesServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AircraftServices_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AircraftServicesServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AircraftServices_DeleteAircrafts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAircraftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AircraftServicesServer).DeleteAircrafts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AircraftServices_DeleteAircrafts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AircraftServicesServer).DeleteAircrafts(ctx, req.(*DeleteAircraftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AircraftServices_ServiceDesc is the grpc.ServiceDesc for AircraftServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AircraftServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "targets.AircraftServices",
	HandlerType: (*AircraftServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAircraft",
			Handler:    _AircraftServices_GetAircraft_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _AircraftServices_GetHistory_Handler,
		},
		{
			MethodName: "DeleteAircrafts",
			Handler:    _AircraftServices_DeleteAircrafts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aircrafts.proto",
}
