// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aircrafts.proto

package aircraft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_CATEGORY_UNKNOWN  Category = 0
	Category_CATEGORY_FRIENDLY Category = 1
	Category_CATEGORY_HOSTILE  Category = 2
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNKNOWN",
		1: "CATEGORY_FRIENDLY",
		2: "CATEGORY_HOSTILE",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNKNOWN":  0,
		"CATEGORY_FRIENDLY": 1,
		"CATEGORY_HOSTILE":  2,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_aircrafts_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_aircrafts_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Alt           float64                `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_aircrafts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Position) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Position) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

type AircraftUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Category      Category               `protobuf:"varint,3,opt,name=category,proto3,enum=targets.Category" json:"category,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AircraftUpdate) Reset() {
	*x = AircraftUpdate{}
	mi := &file_aircrafts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftUpdate) ProtoMessage() {}

func (x *AircraftUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftUpdate.ProtoReflect.Descriptor instead.
func (*AircraftUpdate) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{1}
}

func (x *AircraftUpdate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AircraftUpdate) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *AircraftUpdate) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNKNOWN
}

func (x *AircraftUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_aircrafts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_aircrafts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// ban tin NATS ban broadcast cho cac clients
type AircraftFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           []*AircraftUpdate      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	FrameTimestamp int64                  `protobuf:"varint,2,opt,name=frame_timestamp,json=frameTimestamp,proto3" json:"frame_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AircraftFrame) Reset() {
	*x = AircraftFrame{}
	mi := &file_aircrafts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftFrame) ProtoMessage() {}

func (x *AircraftFrame) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftFrame.ProtoReflect.Descriptor instead.
func (*AircraftFrame) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{4}
}

func (x *AircraftFrame) GetData() []*AircraftUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AircraftFrame) GetFrameTimestamp() int64 {
	if x != nil {
		return x.FrameTimestamp
	}
	return 0
}

type GetAircraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAircraftRequest) Reset() {
	*x = GetAircraftRequest{}
	mi := &file_aircrafts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAircraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAircraftRequest) ProtoMessage() {}

func (x *GetAircraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAircraftRequest.ProtoReflect.Descriptor instead.
func (*GetAircraftRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{5}
}

func (x *GetAircraftRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAircraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AircraftUpdate        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAircraftResponse) Reset() {
	*x = GetAircraftResponse{}
	mi := &file_aircrafts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAircraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAircraftResponse) ProtoMessage() {}

func (x *GetAircraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAircraftResponse.ProtoReflect.Descriptor instead.
func (*GetAircraftResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{6}
}

func (x *GetAircraftResponse) GetData() *AircraftUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteAircraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAircraftsRequest) Reset() {
	*x = DeleteAircraftsRequest{}
	mi := &file_aircrafts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAircraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAircraftsRequest) ProtoMessage() {}

func (x *DeleteAircraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAircraftsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAircraftsRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAircraftsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteAircraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAircraftsResponse) Reset() {
	*x = DeleteAircraftsResponse{}
	mi := &file_aircrafts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAircraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAircraftsResponse) ProtoMessage() {}

func (x *DeleteAircraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAircraftsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAircraftsResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAircraftsResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_aircrafts_proto protoreflect.FileDescriptor

const file_aircrafts_proto_rawDesc = "" +
	"\n" +
	"\x0faircrafts.proto\x12\atargets\"@\n" +
	"\bPosition\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x01R\x03alt\"\x9c\x01\n" +
	"\x0eAircraftUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.targets.PositionR\bposition\x12-\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x11.targets.CategoryR\bcategory\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"#\n" +
	"\x11GetHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"E\n" +
	"\x12GetHistoryResponse\x12/\n" +
	"\tpositions\x18\x01 \x03(\v2\x11.targets.PositionR\tpositions\"e\n" +
	"\rAircraftFrame\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.targets.AircraftUpdateR\x04data\x12'\n" +
	"\x0fframe_timestamp\x18\x02 \x01(\x03R\x0eframeTimestamp\"$\n" +
	"\x12GetAircraftRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"B\n" +
	"\x13GetAircraftResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.targets.AircraftUpdateR\x04data\"*\n" +
	"\x16DeleteAircraftsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"3\n" +
	"\x17DeleteAircraftsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted*M\n" +
	"\bCategory\x12\x14\n" +
	"\x10CATEGORY_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CATEGORY_FRIENDLY\x10\x01\x12\x14\n" +
	"\x10CATEGORY_HOSTILE\x10\x022\xf9\x01\n" +
	"\x10AircraftServices\x12H\n" +
	"\vGetAircraft\x12\x1b.targets.GetAircraftRequest\x1a\x1c.targets.GetAircraftResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.targets.GetHistoryRequest\x1a\x1b.targets.GetHistoryResponse\x12T\n" +
	"\x0fDeleteAircrafts\x12\x1f.targets.DeleteAircraftsRequest\x1a .targets.DeleteAircraftsResponseB\x0fZ\r./pb/aircraftb\x06proto3"

var (
	file_aircrafts_proto_rawDescOnce sync.Once
	file_aircrafts_proto_rawDescData []byte
)

func file_aircrafts_proto_rawDescGZIP() []byte {
	file_aircrafts_proto_rawDescOnce.Do(func() {
		file_aircrafts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aircrafts_proto_rawDesc), len(file_aircrafts_proto_rawDesc)))
	})
	return file_aircrafts_proto_rawDescData
}

var file_aircrafts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aircrafts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_aircrafts_proto_goTypes = []any{
	(Category)(0),                   // 0: targets.Category
	(*Position)(nil),                // 1: targets.Position
	(*AircraftUpdate)(nil),          // 2: targets.AircraftUpdate
	(*GetHistoryRequest)(nil),       // 3: targets.GetHistoryRequest
	(*GetHistoryResponse)(nil),      // 4: targets.GetHistoryResponse
	(*AircraftFrame)(nil),           // 5: targets.AircraftFrame
	(*GetAircraftRequest)(nil),      // 6: targets.GetAircraftRequest
	(*GetAircraftResponse)(nil),     // 7: targets.GetAircraftResponse
	(*DeleteAircraftsRequest)(nil),  // 8: targets.DeleteAircraftsRequest
	(*DeleteAircraftsResponse)(nil), // 9: targets.DeleteAircraftsResponse
}
var file_aircrafts_proto_depIdxs = []int32{
	1, // 0: targets.AircraftUpdate.position:type_name -> targets.Position
	0, // 1: targets.AircraftUpdate.category:type_name -> targets.Category
	1, // 2: targets.GetHistoryResponse.positions:type_name -> targets.Position
	2, // 3: targets.AircraftFrame.data:type_name -> targets.AircraftUpdate
	2, // 4: targets.GetAircraftResponse.data:type_name -> targets.AircraftUpdate
	6, // 5: targets.AircraftServices.GetAircraft:input_type -> targets.GetAircraftRequest
	3, // 6: targets.AircraftServices.GetHistory:input_type -> targets.GetHistoryRequest
	8, // 7: targets.AircraftServices.DeleteAircrafts:input_type -> targets.DeleteAircraftsRequest
	7, // 8: targets.AircraftServices.GetAircraft:output_type -> targets.GetAircraftResponse
	4, // 9: targets.AircraftServices.GetHistory:output_type -> targets.GetHistoryResponse
	9, // 10: targets.AircraftServices.DeleteAircrafts:output_type -> targets.DeleteAircraftsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_aircrafts_proto_init() }
func file_aircrafts_proto_init() {
	if File_aircrafts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aircrafts_proto_rawDesc), len(file_aircrafts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aircrafts_proto_goTypes,
		DependencyIndexes: file_aircrafts_proto_depIdxs,
		EnumInfos:         file_aircrafts_proto_enumTypes,
		MessageInfos:      file_aircrafts_proto_msgTypes,
	}.Build()
	File_aircrafts_proto = out.File
	file_aircrafts_proto_goTypes = nil
	file_aircrafts_proto_depIdxs = nil
}
