// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aircrafts.proto

package aircraft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_CATEGORY_UNKNOWN  Category = 0
	Category_CATEGORY_FRIENDLY Category = 1
	Category_CATEGORY_HOSTILE  Category = 2
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNKNOWN",
		1: "CATEGORY_FRIENDLY",
		2: "CATEGORY_HOSTILE",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNKNOWN":  0,
		"CATEGORY_FRIENDLY": 1,
		"CATEGORY_HOSTILE":  2,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_aircrafts_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_aircrafts_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Alt           float64                `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,5,opt,name=heading,proto3" json:"heading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_aircrafts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Position) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Position) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Position) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Position) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type AircraftIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callsign      string                 `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	DetectionTime int64                  `protobuf:"varint,2,opt,name=detection_time,json=detectionTime,proto3" json:"detection_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AircraftIdentity) Reset() {
	*x = AircraftIdentity{}
	mi := &file_aircrafts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftIdentity) ProtoMessage() {}

func (x *AircraftIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftIdentity.ProtoReflect.Descriptor instead.
func (*AircraftIdentity) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{1}
}

func (x *AircraftIdentity) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *AircraftIdentity) GetDetectionTime() int64 {
	if x != nil {
		return x.DetectionTime
	}
	return 0
}

type AircraftUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Callsign       string                 `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	DetectionTime  int64                  `protobuf:"varint,2,opt,name=detection_time,json=detectionTime,proto3" json:"detection_time,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Position       *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Category       Category               `protobuf:"varint,5,opt,name=category,proto3,enum=targets.Category" json:"category,omitempty"`
	Mode_3A        string                 `protobuf:"bytes,6,opt,name=mode_3a,json=mode3a,proto3" json:"mode_3a,omitempty"`
	Classification string                 `protobuf:"bytes,7,opt,name=classification,proto3" json:"classification,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AircraftUpdate) Reset() {
	*x = AircraftUpdate{}
	mi := &file_aircrafts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftUpdate) ProtoMessage() {}

func (x *AircraftUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftUpdate.ProtoReflect.Descriptor instead.
func (*AircraftUpdate) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{2}
}

func (x *AircraftUpdate) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *AircraftUpdate) GetDetectionTime() int64 {
	if x != nil {
		return x.DetectionTime
	}
	return 0
}

func (x *AircraftUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AircraftUpdate) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *AircraftUpdate) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNKNOWN
}

func (x *AircraftUpdate) GetMode_3A() string {
	if x != nil {
		return x.Mode_3A
	}
	return ""
}

func (x *AircraftUpdate) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aircraft      *AircraftIdentity      `protobuf:"bytes,1,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_aircrafts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryRequest) GetAircraft() *AircraftIdentity {
	if x != nil {
		return x.Aircraft
	}
	return nil
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_aircrafts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// ban tin NATS ban broadcast cho cac clients
type AircraftFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           []*AircraftUpdate      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	FrameTimestamp int64                  `protobuf:"varint,2,opt,name=frame_timestamp,json=frameTimestamp,proto3" json:"frame_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AircraftFrame) Reset() {
	*x = AircraftFrame{}
	mi := &file_aircrafts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftFrame) ProtoMessage() {}

func (x *AircraftFrame) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftFrame.ProtoReflect.Descriptor instead.
func (*AircraftFrame) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{5}
}

func (x *AircraftFrame) GetData() []*AircraftUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AircraftFrame) GetFrameTimestamp() int64 {
	if x != nil {
		return x.FrameTimestamp
	}
	return 0
}

type GetAircraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aircraft      *AircraftIdentity      `protobuf:"bytes,1,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAircraftRequest) Reset() {
	*x = GetAircraftRequest{}
	mi := &file_aircrafts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAircraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAircraftRequest) ProtoMessage() {}

func (x *GetAircraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAircraftRequest.ProtoReflect.Descriptor instead.
func (*GetAircraftRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{6}
}

func (x *GetAircraftRequest) GetAircraft() *AircraftIdentity {
	if x != nil {
		return x.Aircraft
	}
	return nil
}

type GetAircraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AircraftUpdate        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAircraftResponse) Reset() {
	*x = GetAircraftResponse{}
	mi := &file_aircrafts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAircraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAircraftResponse) ProtoMessage() {}

func (x *GetAircraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAircraftResponse.ProtoReflect.Descriptor instead.
func (*GetAircraftResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{7}
}

func (x *GetAircraftResponse) GetData() *AircraftUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateIsPermanentAircraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aircraft      *AircraftIdentity      `protobuf:"bytes,1,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	FromTs        int64                  `protobuf:"varint,2,opt,name=from_ts,json=fromTs,proto3" json:"from_ts,omitempty"`
	ToTs          int64                  `protobuf:"varint,3,opt,name=to_ts,json=toTs,proto3" json:"to_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIsPermanentAircraftsRequest) Reset() {
	*x = UpdateIsPermanentAircraftsRequest{}
	mi := &file_aircrafts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIsPermanentAircraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIsPermanentAircraftsRequest) ProtoMessage() {}

func (x *UpdateIsPermanentAircraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIsPermanentAircraftsRequest.ProtoReflect.Descriptor instead.
func (*UpdateIsPermanentAircraftsRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateIsPermanentAircraftsRequest) GetAircraft() *AircraftIdentity {
	if x != nil {
		return x.Aircraft
	}
	return nil
}

func (x *UpdateIsPermanentAircraftsRequest) GetFromTs() int64 {
	if x != nil {
		return x.FromTs
	}
	return 0
}

func (x *UpdateIsPermanentAircraftsRequest) GetToTs() int64 {
	if x != nil {
		return x.ToTs
	}
	return 0
}

type UpdateIsPermanentAircraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIsPermanentAircraftsResponse) Reset() {
	*x = UpdateIsPermanentAircraftsResponse{}
	mi := &file_aircrafts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIsPermanentAircraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIsPermanentAircraftsResponse) ProtoMessage() {}

func (x *UpdateIsPermanentAircraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIsPermanentAircraftsResponse.ProtoReflect.Descriptor instead.
func (*UpdateIsPermanentAircraftsResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateIsPermanentAircraftsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteAircraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aircrafts     []*AircraftIdentity    `protobuf:"bytes,1,rep,name=aircrafts,proto3" json:"aircrafts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAircraftsRequest) Reset() {
	*x = DeleteAircraftsRequest{}
	mi := &file_aircrafts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAircraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAircraftsRequest) ProtoMessage() {}

func (x *DeleteAircraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAircraftsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAircraftsRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAircraftsRequest) GetAircrafts() []*AircraftIdentity {
	if x != nil {
		return x.Aircrafts
	}
	return nil
}

type DeleteAircraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAircraftsResponse) Reset() {
	*x = DeleteAircraftsResponse{}
	mi := &file_aircrafts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAircraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAircraftsResponse) ProtoMessage() {}

func (x *DeleteAircraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAircraftsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAircraftsResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAircraftsResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GlobalPlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromTs        int64                  `protobuf:"varint,1,opt,name=from_ts,json=fromTs,proto3" json:"from_ts,omitempty"`
	ToTs          int64                  `protobuf:"varint,2,opt,name=to_ts,json=toTs,proto3" json:"to_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalPlaybackRequest) Reset() {
	*x = GlobalPlaybackRequest{}
	mi := &file_aircrafts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalPlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalPlaybackRequest) ProtoMessage() {}

func (x *GlobalPlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalPlaybackRequest.ProtoReflect.Descriptor instead.
func (*GlobalPlaybackRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{12}
}

func (x *GlobalPlaybackRequest) GetFromTs() int64 {
	if x != nil {
		return x.FromTs
	}
	return 0
}

func (x *GlobalPlaybackRequest) GetToTs() int64 {
	if x != nil {
		return x.ToTs
	}
	return 0
}

type PlaybackPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Alt           float64                `protobuf:"fixed64,4,opt,name=alt,proto3" json:"alt,omitempty"`
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	IsPermanent   bool                   `protobuf:"varint,7,opt,name=is_permanent,json=isPermanent,proto3" json:"is_permanent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackPosition) Reset() {
	*x = PlaybackPosition{}
	mi := &file_aircrafts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackPosition) ProtoMessage() {}

func (x *PlaybackPosition) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackPosition.ProtoReflect.Descriptor instead.
func (*PlaybackPosition) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{13}
}

func (x *PlaybackPosition) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlaybackPosition) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *PlaybackPosition) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *PlaybackPosition) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *PlaybackPosition) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlaybackPosition) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *PlaybackPosition) GetIsPermanent() bool {
	if x != nil {
		return x.IsPermanent
	}
	return false
}

type FlightPlayback struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Callsign       string                 `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	DetectionTime  int64                  `protobuf:"varint,2,opt,name=detection_time,json=detectionTime,proto3" json:"detection_time,omitempty"`
	Positions      []*PlaybackPosition    `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	Category       Category               `protobuf:"varint,4,opt,name=category,proto3,enum=targets.Category" json:"category,omitempty"`
	Classification string                 `protobuf:"bytes,5,opt,name=classification,proto3" json:"classification,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlightPlayback) Reset() {
	*x = FlightPlayback{}
	mi := &file_aircrafts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightPlayback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightPlayback) ProtoMessage() {}

func (x *FlightPlayback) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightPlayback.ProtoReflect.Descriptor instead.
func (*FlightPlayback) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{14}
}

func (x *FlightPlayback) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *FlightPlayback) GetDetectionTime() int64 {
	if x != nil {
		return x.DetectionTime
	}
	return 0
}

func (x *FlightPlayback) GetPositions() []*PlaybackPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *FlightPlayback) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNKNOWN
}

func (x *FlightPlayback) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

type GlobalPlaybackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flights       []*FlightPlayback      `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalPlaybackResponse) Reset() {
	*x = GlobalPlaybackResponse{}
	mi := &file_aircrafts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalPlaybackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalPlaybackResponse) ProtoMessage() {}

func (x *GlobalPlaybackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalPlaybackResponse.ProtoReflect.Descriptor instead.
func (*GlobalPlaybackResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{15}
}

func (x *GlobalPlaybackResponse) GetFlights() []*FlightPlayback {
	if x != nil {
		return x.Flights
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromTs        int64                  `protobuf:"varint,1,opt,name=from_ts,json=fromTs,proto3" json:"from_ts,omitempty"`
	ToTs          int64                  `protobuf:"varint,2,opt,name=to_ts,json=toTs,proto3" json:"to_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_aircrafts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{16}
}

func (x *Session) GetFromTs() int64 {
	if x != nil {
		return x.FromTs
	}
	return 0
}

func (x *Session) GetToTs() int64 {
	if x != nil {
		return x.ToTs
	}
	return 0
}

type GetAircraftsByTimeWindowResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AircraftIdentities []*AircraftIdentity    `protobuf:"bytes,1,rep,name=aircraft_identities,json=aircraftIdentities,proto3" json:"aircraft_identities,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAircraftsByTimeWindowResponse) Reset() {
	*x = GetAircraftsByTimeWindowResponse{}
	mi := &file_aircrafts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAircraftsByTimeWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAircraftsByTimeWindowResponse) ProtoMessage() {}

func (x *GetAircraftsByTimeWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAircraftsByTimeWindowResponse.ProtoReflect.Descriptor instead.
func (*GetAircraftsByTimeWindowResponse) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{17}
}

func (x *GetAircraftsByTimeWindowResponse) GetAircraftIdentities() []*AircraftIdentity {
	if x != nil {
		return x.AircraftIdentities
	}
	return nil
}

type GetPlaybackDataByTimeWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aircrafts     []*AircraftIdentity    `protobuf:"bytes,1,rep,name=aircrafts,proto3" json:"aircrafts,omitempty"`
	FromTs        int64                  `protobuf:"varint,2,opt,name=from_ts,json=fromTs,proto3" json:"from_ts,omitempty"`
	ToTs          int64                  `protobuf:"varint,3,opt,name=to_ts,json=toTs,proto3" json:"to_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaybackDataByTimeWindowRequest) Reset() {
	*x = GetPlaybackDataByTimeWindowRequest{}
	mi := &file_aircrafts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaybackDataByTimeWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaybackDataByTimeWindowRequest) ProtoMessage() {}

func (x *GetPlaybackDataByTimeWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaybackDataByTimeWindowRequest.ProtoReflect.Descriptor instead.
func (*GetPlaybackDataByTimeWindowRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlaybackDataByTimeWindowRequest) GetAircrafts() []*AircraftIdentity {
	if x != nil {
		return x.Aircrafts
	}
	return nil
}

func (x *GetPlaybackDataByTimeWindowRequest) GetFromTs() int64 {
	if x != nil {
		return x.FromTs
	}
	return 0
}

func (x *GetPlaybackDataByTimeWindowRequest) GetToTs() int64 {
	if x != nil {
		return x.ToTs
	}
	return 0
}

type GetPlaybackDataBySessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Aircrafts        []*AircraftIdentity    `protobuf:"bytes,1,rep,name=aircrafts,proto3" json:"aircrafts,omitempty"`
	FromTs           int64                  `protobuf:"varint,2,opt,name=from_ts,json=fromTs,proto3" json:"from_ts,omitempty"`
	ToTs             int64                  `protobuf:"varint,3,opt,name=to_ts,json=toTs,proto3" json:"to_ts,omitempty"`
	SampleIntervalMs int64                  `protobuf:"varint,4,opt,name=sample_interval_ms,json=sampleIntervalMs,proto3" json:"sample_interval_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPlaybackDataBySessionRequest) Reset() {
	*x = GetPlaybackDataBySessionRequest{}
	mi := &file_aircrafts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaybackDataBySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaybackDataBySessionRequest) ProtoMessage() {}

func (x *GetPlaybackDataBySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aircrafts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaybackDataBySessionRequest.ProtoReflect.Descriptor instead.
func (*GetPlaybackDataBySessionRequest) Descriptor() ([]byte, []int) {
	return file_aircrafts_proto_rawDescGZIP(), []int{19}
}

func (x *GetPlaybackDataBySessionRequest) GetAircrafts() []*AircraftIdentity {
	if x != nil {
		return x.Aircrafts
	}
	return nil
}

func (x *GetPlaybackDataBySessionRequest) GetFromTs() int64 {
	if x != nil {
		return x.FromTs
	}
	return 0
}

func (x *GetPlaybackDataBySessionRequest) GetToTs() int64 {
	if x != nil {
		return x.ToTs
	}
	return 0
}

func (x *GetPlaybackDataBySessionRequest) GetSampleIntervalMs() int64 {
	if x != nil {
		return x.SampleIntervalMs
	}
	return 0
}

var File_aircrafts_proto protoreflect.FileDescriptor

const file_aircrafts_proto_rawDesc = "" +
	"\n" +
	"\x0faircrafts.proto\x12\atargets\"p\n" +
	"\bPosition\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x01R\x03alt\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x05 \x01(\x01R\aheading\"U\n" +
	"\x10AircraftIdentity\x12\x1a\n" +
	"\bcallsign\x18\x01 \x01(\tR\bcallsign\x12%\n" +
	"\x0edetection_time\x18\x02 \x01(\x03R\rdetectionTime\"\x90\x02\n" +
	"\x0eAircraftUpdate\x12\x1a\n" +
	"\bcallsign\x18\x01 \x01(\tR\bcallsign\x12%\n" +
	"\x0edetection_time\x18\x02 \x01(\x03R\rdetectionTime\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12-\n" +
	"\bposition\x18\x04 \x01(\v2\x11.targets.PositionR\bposition\x12-\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x11.targets.CategoryR\bcategory\x12\x17\n" +
	"\amode_3a\x18\x06 \x01(\tR\x06mode3a\x12&\n" +
	"\x0eclassification\x18\a \x01(\tR\x0eclassification\"J\n" +
	"\x11GetHistoryRequest\x125\n" +
	"\baircraft\x18\x01 \x01(\v2\x19.targets.AircraftIdentityR\baircraft\"E\n" +
	"\x12GetHistoryResponse\x12/\n" +
	"\tpositions\x18\x01 \x03(\v2\x11.targets.PositionR\tpositions\"e\n" +
	"\rAircraftFrame\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.targets.AircraftUpdateR\x04data\x12'\n" +
	"\x0fframe_timestamp\x18\x02 \x01(\x03R\x0eframeTimestamp\"K\n" +
	"\x12GetAircraftRequest\x125\n" +
	"\baircraft\x18\x01 \x01(\v2\x19.targets.AircraftIdentityR\baircraft\"B\n" +
	"\x13GetAircraftResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.targets.AircraftUpdateR\x04data\"\x88\x01\n" +
	"!UpdateIsPermanentAircraftsRequest\x125\n" +
	"\baircraft\x18\x01 \x01(\v2\x19.targets.AircraftIdentityR\baircraft\x12\x17\n" +
	"\afrom_ts\x18\x02 \x01(\x03R\x06fromTs\x12\x13\n" +
	"\x05to_ts\x18\x03 \x01(\x03R\x04toTs\">\n" +
	"\"UpdateIsPermanentAircraftsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x16DeleteAircraftsRequest\x127\n" +
	"\taircrafts\x18\x01 \x03(\v2\x19.targets.AircraftIdentityR\taircrafts\"3\n" +
	"\x17DeleteAircraftsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"E\n" +
	"\x15GlobalPlaybackRequest\x12\x17\n" +
	"\afrom_ts\x18\x01 \x01(\x03R\x06fromTs\x12\x13\n" +
	"\x05to_ts\x18\x02 \x01(\x03R\x04toTs\"\xb9\x01\n" +
	"\x10PlaybackPosition\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\x01R\x03alt\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12!\n" +
	"\fis_permanent\x18\a \x01(\bR\visPermanent\"\xe3\x01\n" +
	"\x0eFlightPlayback\x12\x1a\n" +
	"\bcallsign\x18\x01 \x01(\tR\bcallsign\x12%\n" +
	"\x0edetection_time\x18\x02 \x01(\x03R\rdetectionTime\x127\n" +
	"\tpositions\x18\x03 \x03(\v2\x19.targets.PlaybackPositionR\tpositions\x12-\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x11.targets.CategoryR\bcategory\x12&\n" +
	"\x0eclassification\x18\x05 \x01(\tR\x0eclassification\"K\n" +
	"\x16GlobalPlaybackResponse\x121\n" +
	"\aflights\x18\x01 \x03(\v2\x17.targets.FlightPlaybackR\aflights\"7\n" +
	"\aSession\x12\x17\n" +
	"\afrom_ts\x18\x01 \x01(\x03R\x06fromTs\x12\x13\n" +
	"\x05to_ts\x18\x02 \x01(\x03R\x04toTs\"n\n" +
	" GetAircraftsByTimeWindowResponse\x12J\n" +
	"\x13aircraft_identities\x18\x01 \x03(\v2\x19.targets.AircraftIdentityR\x12aircraftIdentities\"\x8b\x01\n" +
	"\"GetPlaybackDataByTimeWindowRequest\x127\n" +
	"\taircrafts\x18\x01 \x03(\v2\x19.targets.AircraftIdentityR\taircrafts\x12\x17\n" +
	"\afrom_ts\x18\x02 \x01(\x03R\x06fromTs\x12\x13\n" +
	"\x05to_ts\x18\x03 \x01(\x03R\x04toTs\"\xb6\x01\n" +
	"\x1fGetPlaybackDataBySessionRequest\x127\n" +
	"\taircrafts\x18\x01 \x03(\v2\x19.targets.AircraftIdentityR\taircrafts\x12\x17\n" +
	"\afrom_ts\x18\x02 \x01(\x03R\x06fromTs\x12\x13\n" +
	"\x05to_ts\x18\x03 \x01(\x03R\x04toTs\x12,\n" +
	"\x12sample_interval_ms\x18\x04 \x01(\x03R\x10sampleIntervalMs*M\n" +
	"\bCategory\x12\x14\n" +
	"\x10CATEGORY_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CATEGORY_FRIENDLY\x10\x01\x12\x14\n" +
	"\x10CATEGORY_HOSTILE\x10\x022\xf3\x05\n" +
	"\x10AircraftServices\x12H\n" +
	"\vGetAircraft\x12\x1b.targets.GetAircraftRequest\x1a\x1c.targets.GetAircraftResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.targets.GetHistoryRequest\x1a\x1b.targets.GetHistoryResponse\x12T\n" +
	"\x11GetGlobalPlayback\x12\x1e.targets.GlobalPlaybackRequest\x1a\x1f.targets.GlobalPlaybackResponse\x12u\n" +
	"\x1aUpdateIsPermanentAircrafts\x12*.targets.UpdateIsPermanentAircraftsRequest\x1a+.targets.UpdateIsPermanentAircraftsResponse\x12T\n" +
	"\x0fDeleteAircrafts\x12\x1f.targets.DeleteAircraftsRequest\x1a .targets.DeleteAircraftsResponse\x12W\n" +
	"\x18GetAircraftsByTimeWindow\x12\x10.targets.Session\x1a).targets.GetAircraftsByTimeWindowResponse\x12k\n" +
	"\x1bGetPlaybackDataByTimeWindow\x12+.targets.GetPlaybackDataByTimeWindowRequest\x1a\x1f.targets.GlobalPlaybackResponse\x12e\n" +
	"\x18GetPlaybackDataBySession\x12(.targets.GetPlaybackDataBySessionRequest\x1a\x1f.targets.GlobalPlaybackResponseB\x0fZ\r./pb/aircraftb\x06proto3"

var (
	file_aircrafts_proto_rawDescOnce sync.Once
	file_aircrafts_proto_rawDescData []byte
)

func file_aircrafts_proto_rawDescGZIP() []byte {
	file_aircrafts_proto_rawDescOnce.Do(func() {
		file_aircrafts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aircrafts_proto_rawDesc), len(file_aircrafts_proto_rawDesc)))
	})
	return file_aircrafts_proto_rawDescData
}

var file_aircrafts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aircrafts_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_aircrafts_proto_goTypes = []any{
	(Category)(0),                              // 0: targets.Category
	(*Position)(nil),                           // 1: targets.Position
	(*AircraftIdentity)(nil),                   // 2: targets.AircraftIdentity
	(*AircraftUpdate)(nil),                     // 3: targets.AircraftUpdate
	(*GetHistoryRequest)(nil),                  // 4: targets.GetHistoryRequest
	(*GetHistoryResponse)(nil),                 // 5: targets.GetHistoryResponse
	(*AircraftFrame)(nil),                      // 6: targets.AircraftFrame
	(*GetAircraftRequest)(nil),                 // 7: targets.GetAircraftRequest
	(*GetAircraftResponse)(nil),                // 8: targets.GetAircraftResponse
	(*UpdateIsPermanentAircraftsRequest)(nil),  // 9: targets.UpdateIsPermanentAircraftsRequest
	(*UpdateIsPermanentAircraftsResponse)(nil), // 10: targets.UpdateIsPermanentAircraftsResponse
	(*DeleteAircraftsRequest)(nil),             // 11: targets.DeleteAircraftsRequest
	(*DeleteAircraftsResponse)(nil),            // 12: targets.DeleteAircraftsResponse
	(*GlobalPlaybackRequest)(nil),              // 13: targets.GlobalPlaybackRequest
	(*PlaybackPosition)(nil),                   // 14: targets.PlaybackPosition
	(*FlightPlayback)(nil),                     // 15: targets.FlightPlayback
	(*GlobalPlaybackResponse)(nil),             // 16: targets.GlobalPlaybackResponse
	(*Session)(nil),                            // 17: targets.Session
	(*GetAircraftsByTimeWindowResponse)(nil),   // 18: targets.GetAircraftsByTimeWindowResponse
	(*GetPlaybackDataByTimeWindowRequest)(nil), // 19: targets.GetPlaybackDataByTimeWindowRequest
	(*GetPlaybackDataBySessionRequest)(nil),    // 20: targets.GetPlaybackDataBySessionRequest
}
var file_aircrafts_proto_depIdxs = []int32{
	1,  // 0: targets.AircraftUpdate.position:type_name -> targets.Position
	0,  // 1: targets.AircraftUpdate.category:type_name -> targets.Category
	2,  // 2: targets.GetHistoryRequest.aircraft:type_name -> targets.AircraftIdentity
	1,  // 3: targets.GetHistoryResponse.positions:type_name -> targets.Position
	3,  // 4: targets.AircraftFrame.data:type_name -> targets.AircraftUpdate
	2,  // 5: targets.GetAircraftRequest.aircraft:type_name -> targets.AircraftIdentity
	3,  // 6: targets.GetAircraftResponse.data:type_name -> targets.AircraftUpdate
	2,  // 7: targets.UpdateIsPermanentAircraftsRequest.aircraft:type_name -> targets.AircraftIdentity
	2,  // 8: targets.DeleteAircraftsRequest.aircrafts:type_name -> targets.AircraftIdentity
	14, // 9: targets.FlightPlayback.positions:type_name -> targets.PlaybackPosition
	0,  // 10: targets.FlightPlayback.category:type_name -> targets.Category
	15, // 11: targets.GlobalPlaybackResponse.flights:type_name -> targets.FlightPlayback
	2,  // 12: targets.GetAircraftsByTimeWindowResponse.aircraft_identities:type_name -> targets.AircraftIdentity
	2,  // 13: targets.GetPlaybackDataByTimeWindowRequest.aircrafts:type_name -> targets.AircraftIdentity
	2,  // 14: targets.GetPlaybackDataBySessionRequest.aircrafts:type_name -> targets.AircraftIdentity
	7,  // 15: targets.AircraftServices.GetAircraft:input_type -> targets.GetAircraftRequest
	4,  // 16: targets.AircraftServices.GetHistory:input_type -> targets.GetHistoryRequest
	13, // 17: targets.AircraftServices.GetGlobalPlayback:input_type -> targets.GlobalPlaybackRequest
	9,  // 18: targets.AircraftServices.UpdateIsPermanentAircrafts:input_type -> targets.UpdateIsPermanentAircraftsRequest
	11, // 19: targets.AircraftServices.DeleteAircrafts:input_type -> targets.DeleteAircraftsRequest
	17, // 20: targets.AircraftServices.GetAircraftsByTimeWindow:input_type -> targets.Session
	19, // 21: targets.AircraftServices.GetPlaybackDataByTimeWindow:input_type -> targets.GetPlaybackDataByTimeWindowRequest
	20, // 22: targets.AircraftServices.GetPlaybackDataBySession:input_type -> targets.GetPlaybackDataBySessionRequest
	8,  // 23: targets.AircraftServices.GetAircraft:output_type -> targets.GetAircraftResponse
	5,  // 24: targets.AircraftServices.GetHistory:output_type -> targets.GetHistoryResponse
	16, // 25: targets.AircraftServices.GetGlobalPlayback:output_type -> targets.GlobalPlaybackResponse
	10, // 26: targets.AircraftServices.UpdateIsPermanentAircrafts:output_type -> targets.UpdateIsPermanentAircraftsResponse
	12, // 27: targets.AircraftServices.DeleteAircrafts:output_type -> targets.DeleteAircraftsResponse
	18, // 28: targets.AircraftServices.GetAircraftsByTimeWindow:output_type -> targets.GetAircraftsByTimeWindowResponse
	16, // 29: targets.AircraftServices.GetPlaybackDataByTimeWindow:output_type -> targets.GlobalPlaybackResponse
	16, // 30: targets.AircraftServices.GetPlaybackDataBySession:output_type -> targets.GlobalPlaybackResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_aircrafts_proto_init() }
func file_aircrafts_proto_init() {
	if File_aircrafts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aircrafts_proto_rawDesc), len(file_aircrafts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aircrafts_proto_goTypes,
		DependencyIndexes: file_aircrafts_proto_depIdxs,
		EnumInfos:         file_aircrafts_proto_enumTypes,
		MessageInfos:      file_aircrafts_proto_msgTypes,
	}.Build()
	File_aircrafts_proto = out.File
	file_aircrafts_proto_goTypes = nil
	file_aircrafts_proto_depIdxs = nil
}
