syntax = "proto3";

package targets;

option go_package = "./pb/aircraft";

enum Category{
    CATEGORY_UNKNOWN = 0;
    CATEGORY_FRIENDLY = 1;
    CATEGORY_HOSTILE = 2;
}

message Position{
        double lat = 1;
        double lng = 2;
        double alt = 3;
        double speed = 4;
        double heading = 5;
}

message AircraftIdentity {
    string callsign = 1;     
    int64 detection_time = 2; 
}

message AircraftUpdate {
    string callsign = 1;
    int64 detection_time = 2;

    int64 timestamp = 3;
    Position position = 4;
    

    Category category = 5;
    string mode_3a = 6;
    string classification = 7;
}
message GetHistoryRequest{
    AircraftIdentity aircraft = 1;

}


message GetHistoryResponse{
    repeated Position positions = 1;
}

// Luong stream

// ban tin NATS ban broadcast cho cac clients
message AircraftFrame{
    repeated AircraftUpdate data = 1;
    int64 frame_timestamp = 2;
}

message GetAircraftRequest{
    AircraftIdentity aircraft = 1;
}

message GetAircraftResponse{
    AircraftUpdate data = 1;
}


message UpdateIsPermanentAircraftsRequest{
    AircraftIdentity aircraft = 1;
    int64 from_ts = 2; 
    int64 to_ts = 3;
}

message UpdateIsPermanentAircraftsResponse {
    bool success = 1;
}


message DeleteAircraftsRequest{
    repeated AircraftIdentity aircrafts = 1;
}

message DeleteAircraftsResponse{
    bool deleted = 1;
}

// tai hien dong/tinh

message GlobalPlaybackRequest {
    int64 from_ts = 1;
    int64 to_ts = 2;
}

message PlaybackPosition {
    int64 timestamp = 1;
    double lat = 2;
    double lng = 3;
    double alt = 4;
    double speed = 5;
    double heading = 6;
    bool is_permanent = 7; 
}

message FlightPlayback {
    string callsign = 1;
    int64 detection_time = 2;
    repeated PlaybackPosition positions = 3; 
    Category category = 4;
    string classification = 5;
}


message GlobalPlaybackResponse {
    repeated FlightPlayback flights = 1; 
}

message Session {
    int64 from_ts = 1;
    int64 to_ts = 2;
}

message GetAircraftsByTimeWindowResponse{
    repeated AircraftIdentity aircraft_identities = 1;
}


message GetPlaybackDataByTimeWindowRequest {
    repeated AircraftIdentity aircrafts = 1;
    int64 from_ts = 2;
    int64 to_ts = 3;
}

message GetPlaybackDataBySessionRequest {
    repeated AircraftIdentity aircrafts = 1;
    int64 from_ts = 2;
    int64 to_ts = 3;
    int64 sample_interval_ms = 4;
}

service AircraftServices{
    rpc GetAircraft(GetAircraftRequest) returns (GetAircraftResponse); //  lay thong tin 1 may bay
    rpc GetHistory(GetHistoryRequest)   returns (GetHistoryResponse); // lay lich su quy dao 1 may bay

    // get all information from all targets trong 1 khoang thoi gian de phat lai dong
    rpc GetGlobalPlayback(GlobalPlaybackRequest)   returns (GlobalPlaybackResponse);

    rpc UpdateIsPermanentAircrafts(UpdateIsPermanentAircraftsRequest) returns (UpdateIsPermanentAircraftsResponse);

    rpc DeleteAircrafts(DeleteAircraftsRequest)  returns (DeleteAircraftsResponse); // xoa cold data (clients call this function)

    rpc GetAircraftsByTimeWindow(Session)   returns (GetAircraftsByTimeWindowResponse);

    rpc GetPlaybackDataByTimeWindow(GetPlaybackDataByTimeWindowRequest) returns (GlobalPlaybackResponse);

    rpc GetPlaybackDataBySession(GetPlaybackDataBySessionRequest) returns (GlobalPlaybackResponse);
}


// to-do : sua lai be, fe de cac tinh nang cu chay duoc (vi them cac truong cua database)
