name: Deploy Backend Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: build backend
        run: go build -o flightsim-be ./cmd/main.go

      - name: Package to Debian (.deb)
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
          nfpm package --packager deb --target flightsim-be.deb
        
     
      - name: Install and restart service local
        run: |
          sudo dpkg -i flightsim-be.deb
          sudo systemctl daemon-reload
          sudo systemctl enable flightsim-be
          sudo systemctl restart flightsim-be